// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ofgem.Database.GBI.Users.Infrastructure;

#nullable disable

namespace Ofgem.Database.GBI.Users.Infrastructure.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    [Migration("20230818111024_RenamePrimaryKeyColumns")]
    partial class RenamePrimaryKeyColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ofgem.Database.GBI.Users.Domain.Entities.ExternalUser", b =>
                {
                    b.Property<Guid>("ExternalUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("ExternalUserId");

                    b.HasIndex("EmailAddress")
                        .IsUnique();

                    b.HasIndex("ProviderUserId")
                        .IsUnique()
                        .HasFilter("[ProviderUserId] IS NOT NULL");

                    b.HasIndex("SupplierId");

                    b.ToTable("ExternalUsers");
                });

            modelBuilder.Entity("Ofgem.Database.GBI.Users.Domain.Entities.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SupplierId");

                    b.HasIndex("SupplierName")
                        .IsUnique();

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            SupplierId = 1,
                            SupplierName = "EON"
                        },
                        new
                        {
                            SupplierId = 2,
                            SupplierName = "EDF"
                        },
                        new
                        {
                            SupplierId = 3,
                            SupplierName = "SPW"
                        },
                        new
                        {
                            SupplierId = 4,
                            SupplierName = "SSE"
                        },
                        new
                        {
                            SupplierId = 5,
                            SupplierName = "BGT"
                        },
                        new
                        {
                            SupplierId = 6,
                            SupplierName = "NPW"
                        },
                        new
                        {
                            SupplierId = 7,
                            SupplierName = "FUL"
                        },
                        new
                        {
                            SupplierId = 8,
                            SupplierName = "UTW"
                        },
                        new
                        {
                            SupplierId = 9,
                            SupplierName = "COP"
                        },
                        new
                        {
                            SupplierId = 10,
                            SupplierName = "OVO"
                        },
                        new
                        {
                            SupplierId = 11,
                            SupplierName = "UTA"
                        },
                        new
                        {
                            SupplierId = 12,
                            SupplierName = "XEN"
                        },
                        new
                        {
                            SupplierId = 13,
                            SupplierName = "SPK"
                        },
                        new
                        {
                            SupplierId = 14,
                            SupplierName = "EEN"
                        },
                        new
                        {
                            SupplierId = 15,
                            SupplierName = "FLO"
                        },
                        new
                        {
                            SupplierId = 16,
                            SupplierName = "HUD"
                        },
                        new
                        {
                            SupplierId = 17,
                            SupplierName = "BLB"
                        },
                        new
                        {
                            SupplierId = 18,
                            SupplierName = "OCT"
                        },
                        new
                        {
                            SupplierId = 19,
                            SupplierName = "GNE"
                        },
                        new
                        {
                            SupplierId = 20,
                            SupplierName = "EGE"
                        },
                        new
                        {
                            SupplierId = 21,
                            SupplierName = "AVR"
                        },
                        new
                        {
                            SupplierId = 22,
                            SupplierName = "SHL"
                        },
                        new
                        {
                            SupplierId = 23,
                            SupplierName = "SOE"
                        },
                        new
                        {
                            SupplierId = 24,
                            SupplierName = "RHE"
                        },
                        new
                        {
                            SupplierId = 25,
                            SupplierName = "TNK"
                        },
                        new
                        {
                            SupplierId = 26,
                            SupplierName = "PLA"
                        },
                        new
                        {
                            SupplierId = 27,
                            SupplierName = "ISP"
                        },
                        new
                        {
                            SupplierId = 28,
                            SupplierName = "UPL"
                        },
                        new
                        {
                            SupplierId = 29,
                            SupplierName = "ECY"
                        },
                        new
                        {
                            SupplierId = 30,
                            SupplierName = "BRI"
                        },
                        new
                        {
                            SupplierId = 31,
                            SupplierName = "ESB"
                        },
                        new
                        {
                            SupplierId = 32,
                            SupplierName = "IGL"
                        },
                        new
                        {
                            SupplierId = 33,
                            SupplierName = "TOE"
                        },
                        new
                        {
                            SupplierId = 34,
                            SupplierName = "FOX"
                        },
                        new
                        {
                            SupplierId = 35,
                            SupplierName = "PES"
                        });
                });

            modelBuilder.Entity("Ofgem.Database.GBI.Users.Domain.Entities.ExternalUser", b =>
                {
                    b.HasOne("Ofgem.Database.GBI.Users.Domain.Entities.Supplier", "Supplier")
                        .WithMany("ExternalUsers")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Ofgem.Database.GBI.Users.Domain.Entities.Supplier", b =>
                {
                    b.Navigation("ExternalUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
